### ISSUE TITLE
Is there a chance to get a ColorItem?

### ISSUE THREAD

**Issue by crsprsp** [tommasomarchionni/homebridge-openHAB#12]
would be GREAT to get my Hue running....

**Comment by tommasomarchionni** [comment]
is supported color item in openHAB 1.x? i have a problem setting my zipato lamp so i can't try a working color item.

**Comment by crsprsp** [comment]
Yes sure ColorItems are supported in Openhab1.x
Can i assist you with testing? I have several Hue here.

Bye, Rico

**Comment by tommasomarchionni** [comment]
Thanks if you want i have create color item channel in gitter.
https://gitter.im/tommasomarchionni/homebridge-openHAB/coloritem?utm_source=share-link&utm_medium=link&utm_campaign=share-link
