### ISSUE TITLE
ThermostatItem minor issues

### ISSUE THREAD

**Issue by redhell** [tommasomarchionni/homebridge-openHAB#14]
Hello @tommasomarchionni,

the thermostatItem works good! 

I want to report a minor issue:
In the Elegato Eve App (iOS) there is now a new target temperature item but the current temperature is not visible. But if i ask siri about the current temperature it will answer me the correct temperature.
So this could be a cosmetical issue.

As a feature request can you add a humidity sensor?

**Comment by tommasomarchionni** [comment]
I will check the issue in the next days while i will release the humidity sensor feature tomorrow ;)

**Comment by tommasomarchionni** [comment]
I have checked "target temperature" in Elegato Eve App, you can see current ambient temperature when you click in the arrow. You can see in these screenshots:
![target-temperature-1](https://cloud.githubusercontent.com/assets/8122764/13021694/cdea50ac-d1dc-11e5-9ed0-992278a77fd1.PNG)
![target-temperature-2](https://cloud.githubusercontent.com/assets/8122764/13021693/cdc79abc-d1dc-11e5-964f-820d18d621e5.PNG)

**Comment by tommasomarchionni** [comment]
Now with homebridge-openhab@0.1.31 you can use CurrentRelativeHumidityItem in itemSubType attribute for humidity in Thermostat Item.

**Comment by redhell** [comment]
Works thanks!

I already found that view in your screenshot but i thought that the view like the TemperatureSensorItem would be visible.
