### ISSUE TITLE
how to define outlet or light items?

### ISSUE THREAD

**Issue by snizzleorg** [tommasomarchionni/homebridge-openHAB#2]
currently switch items exist. iOS recognises now all switches as lamps. can they also somehow be defined as outlets? maybe via customAttrs?

**Comment by jdwhite** [comment]
Or how about fans versus lights so when I say "turn on the lights" my ceiling fan doesn't turn on?

**Comment by tommasomarchionni** [comment]
Thank you for your feedback! I will add this feature via customAttrs in the next days.

**Comment by jdwhite** [comment]
Thanks! Looking forward to it.

**Comment by snizzleorg** [comment]
Great! Thanks! Any idea about other types - smoke detectors motion detectors etc? will this be possible at all?

**Comment by ssvenn** [comment]
I would really love to see an item type for garage doors so you could use "open" and "close", I tried naming a switch "garage door" so i could say "turn on garage door" but Siri catches "garage" and complains about not finding any garage openers.

The final thing on the wishlist is lock items so you could say "unlock the front door", that should cover most equipment on the market right now.

**Comment by snizzleorg** [comment]
As I see there is a couple of items now. Lightbulb, Fan etc.  I however would need a outlet item (for things like video projector etc). When defined as switch items somehow siri always thinks they are lamps.

**Comment by snizzleorg** [comment]
those are the available types in homekit:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by tommasomarchionni** [comment]
Outlet added! ;)

**Comment by snizzleorg** [comment]
Cool! thanks. I will try it out tomorrow and let you know how!

**Comment by snizzleorg** [comment]
Works beautifully now. Thanks!
