### ISSUE TITLE
Is there no support for temperature items?

### ISSUE THREAD

**Issue by alexbartisro** [tommasomarchionni/homebridge-openHAB#3]
First of all, great job!

Second, if I add a temperature item to my sitemap I get

Platform - The widget 'Bedroom Temperature' of type NumberItem is an item not handled

**Comment by tommasomarchionni** [comment]
Thank you! I added this feature now, let me know if it works so i can close the issue.

**Comment by alexbartisro** [comment]
Awesome! I'll try in about 9 hours, when I get back from work. Thank you!

**Comment by alexbartisro** [comment]
It just crashes now. Installed with npm update

`/usr/lib/node_modules/homebridge-openhab/items/AbstractItem.js:75
    return new exports[this.itemType](this.widget,this.platform,this.homebridge);
           ^

TypeError: exports[this.itemType] is not a function
    at AbstractItem.getItem (/usr/lib/node_modules/homebridge-openhab/items/AbstractItem.js:75:12)
    at exports.Factory.parseSitemap (/usr/lib/node_modules/homebridge-openhab/libs/ItemFactory.js:39:38)
    at Request._callback (/usr/lib/node_modules/homebridge-openhab/index.js:86:34)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openhab/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openhab/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openhab/node_modules/request/request.js:962:12)`

**Comment by alexbartisro** [comment]
Yep. Crashes with both versions 16 and 17. I've reverted to 15 and it works fine.

**Comment by tommasomarchionni** [comment]
Can you try now? It crashes because you should set itemType in customAttrs to TemperatureSensorItem. Now every numberItem of openHAB is set to default to TemperatureSensorItem.

**Comment by alexbartisro** [comment]
I don't get the configuration part. I don't have any item set in my config.json. All of them are loaded from the sitemap. Except this case, why should I add individual items besides pointing it to the sitemap?

**Comment by tommasomarchionni** [comment]
You should add openhab's item in customAttrs only when you need to define special item in HomeKit catalog. For example if you want to define a switch such as a lightbulb. So you can say to Siri to switch on all Lamps without switch on the other switch (Fan, Outlet, etc.).

**Comment by alexbartisro** [comment]
Ah, ok, no I get it. Thank you!

Updated, it works, thank you!

**Comment by alexbartisro** [comment]
One more question, sorry about this!

Do you have any idea why siri doesn't recognize the asking about temperature, but knows if I ask how hot is it? http://imgur.com/EOKiews

**Comment by snizzleorg** [comment]
Don't know. but Siri is strange sometimes. For some weeks "turn the lights on worked", however "turn the lights off" didn't now it works... I think apple needs to do some fixing

**Comment by alexbartisro** [comment]
Yeah, I guess you're right. Saw the same thing with a dimmer, when I first set up homebridge. Turn on worked, but set value didn't. After a couple of hours, `set lights at XX percent` started working.
