### ISSUE TITLE
Openhab2 ?

### ISSUE THREAD

**Issue by belmondo2001** [tommasomarchionni/homebridge-openHAB#5]
Hello,
great Job.
Is it planned to work with openhab2.
Here a sample output from http://192.168.100.30:8080/rest/sitemaps/homekit?type=json

{"name":"homekit","label":"homekit","link":"http://192.168.100.30:8080/rest/sitemaps/homekit","homepage":{"id":"homekit","title":"homekit","link":"http://192.168.100.30:8080/rest/sitemaps/homekit/homekit","leaf":false,"widgets":[{"widgetId":"homekit_0","type":"Slider","label":"Stehlampe","icon":"slider","mappings":[],"switchSupport":false,"sendFrequency":0,"item":{"link":"http://192.168.100.30:8080/rest/items/DIMMER_EG_WZ_STEHLAMPE","state":"0","type":"DimmerItem","name":"DIMMER_EG_WZ_STEHLAMPE","label":"Stehlampe","category":"slider","tags":[],"groupNames":["gEG_WZ","gBELEUCHTUNG"]},"widgets":[]}]}}

**Comment by snizzleorg** [comment]
not sure if this is necessary as there is a homekit binding for openhab2

**Comment by tommasomarchionni** [comment]
In the next weeks i will install openHAB 2 and then i try to integrate with this plugin.

**Comment by llamahunter** [comment]
As far as I know, openHAB 2 dropped WebSockets support, which this is using to get status updates from the openHAB server.  Some re-architecture to use long polling http requests will be needed.

**Comment by gupta-ash** [comment]
Tom - Any updates on OpenHab2 support ? HomeKit doesn't support all devices, so it would be great if you could support OpenHab2

**Comment by matushromada** [comment]
I'm also planning to use homebridge with OpenHab2 as the integrated OpenHab2 binding supports only limited types of devices. Any updates on this? Thanks

**Comment by AndreWeberHH** [comment]
Are there any plans to support OH2?

**Comment by tommasomarchionni** [comment]
I have just released a new [repository](https://github.com/tommasomarchionni/homebridge-openhab2) with support for openHAB2.
